apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-recommendation-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-recommendation-api
  template:
    metadata:
      labels:
        app: job-recommendation-api
    spec:
      containers:
      - name: job-recommendation-api
        image: job_recommendation_api
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: job-recommendation-api-service
spec:
  selector:
    app: job-recommendation-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
